### ISSUE TITLE
Feel free to add any data structures and algorithms programs which are not currently present to the repository.

### ISSUE THREAD

**Issue by nishihere19** [nishihere19/DSA#1]

**Comment by kartik-ey1** [comment]
HEY! I AHVE SOME GOOD DSA ALGOS AND PROBLEM 
I WANT TO CONTRIBUTE IN THIS, CAN YOU ASSIGN THIS TO ME ?

**Comment by nishihere19** [comment]
Sure, go ahead.

**Comment by Sai-Pavan-Nooney** [comment]
Hi, I want to contribute to this. Can you assign this to me?

**Comment by vivekarora-02** [comment]
Hey there, I would like to contribute to this issue. Can you please assign me?
I have many intresting Algos and very neat codes for DS as well.
ThankYou!.

**Comment by nishihere19** [comment]
Yes, add any data-structures/algorithms programs which are currently not present in the repo. PRs are welcome.

**Comment by Sanket2055** [comment]
Hello sir , i would like contribute some algo on graph traversal and string matching ,  please assign me this issue  Thank you!!

**Comment by Sanket2055** [comment]
Hello @nishihere19  sir , i would like contribute some algo on graph traversal and string matching , please assign me this issue Thank you!!

**Comment by kunal-umap** [comment]
I would like to contribute to this issue.
I want to add DNF sort !
 Can you please assign me?

**Comment by nishihere19** [comment]
Hacktoberfest is not accepting any collection based repos like DSA. Hence closing this issue. Thanks for showing interest in contributing.

**Comment by nishihere19** [comment]
People can still contribute and PRs will be accepted.
