### ISSUE TITLE
Add contributors section to the README.md

### ISSUE THREAD

**Issue by nishihere19** [nishihere19/DSA#5]

**Comment by AcousticCh** [comment]
may i?

**Comment by nishihere19** [comment]
Sure @AcousticCh , go ahead!

**Comment by AcousticCh** [comment]
the dynamic url did not update on my endpoint once the PR went through, if this is still an issue in 20 hours or so id be happy to come on here now and then and keep that updated manually, thank you again i never knew how much someone could with a markdown file and a short read on it
