### ISSUE TITLE
Add Counting Sort Algorithm

### ISSUE THREAD

**Issue by ujju20** [nishihere19/DSA#6]
I want to add one sorting algorithm counting sort.

**Comment by nishihere19** [comment]
Sure, you can add.

**Comment by ujju20** [comment]
I want to contribute via Hacktober fest

**Comment by BharaniSri10** [comment]
hey @ujju20  can you please assign this to me? i will do it

**Comment by ujju20** [comment]
> hey @ujju20 can you please assign this to me? i will do it

It has done bro
You can create your own issues and then the maintainer will assign them to you.
